version: '3'
services:
  http-projekt:
    image: php:apache
    ports:
      - 4000:80
    volumes:
      - C:\Users\jakub.kuziola\Desktop\nauka php\projekt:/var/www/html
  mysqll:
    image: mysql:8
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
    volumes:
      - C:\Users\jakub.kuziola\Desktop\nauka php\projekt\db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: tgyfvaeohqugfteqr
      MYSQL_DATABASE: strona
      MYSQL_USER: strona
      MYSQL_PASSWORD: ekliwhgcgbfiwhfruehvbfwjvglfrh
